import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/sections/Footer';
import { Navbar } from '@/components/sections/Navbar';

const plusJakarta = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${plusJakarta.variable} font-sans antialiased`}>
        <div className="flex flex-col min-h-screen max-w-6xl mx-auto px-4 sm:px-8 lg:px-12">
          <Navbar />
          <main className="grow w-full mt-24 md:mt-32">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
